src/Entity/Article.php
<?php

namespace App\Entity;

use AllowDynamicProperties;
use App\Repository\ArticleRepository;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Tag;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;

#[AllowDynamicProperties]
#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: ArticleRepository::class)]

class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?\DateTime $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[Vich\UploadableField(mapping: 'images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'article')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'articles')]
    #[ORM\JoinTable(name: 'tag_article')]
    private Collection $tags;

    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'article')]
    private Collection $comments;

    #[ORM\Column(length: 255, unique: true)]
    #[Gedmo\Slug(fields: ["title"])]
    private ?string $slug;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->setCreatedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getUserIdAsString(): string
    {
        return $this->user_id ? (string) $this->user_id->getId() : 'N/A';
    }

    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Tag;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('tags', EntityType::class, [
                'class' => Tag::class,
                'choice_label' => 'name',
                'expanded' => true,
                'multiple' => true,
            ])
            ->add('imageFile', FileType::class, [
                'label' => 'Ajouter une image',
                'required' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Core\Security;
use Knp\Component\Pager\PaginatorInterface; 
use Doctrine\Persistence\ManagerRegistry;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(Request $request, PaginatorInterface $paginator, ManagerRegistry $doctrine): Response
    {
        $donnees = $doctrine->getRepository(Article::class)->findBy([],['createdAt' => 'desc']);

        $articles = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1), 6 // Nombre de résultats par page
        );
        
        return $this->render('article/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        $article = new Article();
        $article->setUserId($user);

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}-{slug}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article, Request $request, CommentRepository $commentRepository): Response
    {
        $comments = $commentRepository->findBy(['article' => $article]);

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setArticle($article);
            $comment->setUserId($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_show', ['id' => $article->getId(), 'slug' => $article->getSlug()]);
        }

        return $this->render('article/show.html.twig', [
            'article' => $article,
            'comments' => $comments,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setUpdatedAt(new \DateTime());

            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}" >
    <button class="btn btn-outline btn-danger btn-login"><i class="fa-solid fa-trash"></i></button>
</form>

templates/article/_form.html.twig
{{ form_start(form, {'attr': {'class': 'needs-validation'}}) }}

    <div class="mb-3">
        {{ form_row(form.title, {'label': 'Titre', 'attr': {'class': 'form-control', 'placeholder': 'Saisissez un titre...'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.content, {'label': 'Contenu', 'attr': {'class': 'form-control', 'placeholder': 'Saisissez l\'article...'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.imageFile, {'label': 'Ajouter une image', 'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-4">
        {{ form_label(form.tags, 'Tags associés') }}
        {% if form.tags is empty %}
            <p>Aucun tag disponible.</p>
        {% else %}
            {% for tag in form.tags %}
                <div class="form-check">
                    {{ form_widget(tag, {'attr': {'class': 'form-check-input'}}) }}
                    {{ form_label(tag, null, {'label_attr': {'class': 'form-check-label'}}) }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="d-flex justify-content-center mt-4">
        <button class="btn btn-block btn-signup me-3">{{ button_label|default('Save') }}</button>
        <a href="{{ path('app_article_index') }}" class="btn btn-outline btn-login">Retourner à la liste</a>
    </div>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{article.title}} - ActuG{% endblock %}

{% block body %}
    {% if app.user %}
        <div class="container">
            <div class="row justify-content-center mt-5">
                <div class="col-md-6">
                    <h1 class="font-weight-normal text-center mb-4">Modifier l'article n°{{article.id}} : {{article.title}}</h1>

                    {{ include('article/_form.html.twig', {'button_label': 'Modifier'}) }}

                    <div class="d-flex justify-content-center mt-4 ">
                        {% if app.user %}
                            {% if is_granted('ROLE_ADMIN') %}
                                {{ include('article/_delete_form.html.twig') }}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles - ActuG{% endblock %}

{% block body %}
    <h1 class="font-weight-normal text-center mb-4">Liste des articles</h1>

    <div class="row d-flex justify-content-center">
        {% for article in articles %}

            <div class="card miniature col-4 col-sm-3" >
                <a href="{{ path('app_article_show', {'id': article.id, 'slug': article.slug|default('slug')}) }}" class="text-center text-uppercase text-decoration-none">
                    <img class='miniature' src="{{ asset('assets/images/articles/' ~ article.imageName) }}">
                    <div class='container'><p class="mt-3">{{article.title}}</p></div></a>
                    <span class="text-center">Publié(e) par {{article.userId.firstname}} {{article.userId.lastname}}</span>
            </div>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
       
    </div>

    <div class="d-flex justify-content-center">
         {{ knp_pagination_render(articles) }}
    </div>

    {% if app.user %}
        <div class="d-flex justify-content-center mt-3">
            <a href="{{ path('app_article_new') }}" class="btn btn-block btn-signup me-3">Créer un nouvel article</a>
        </div>
    {% endif %}

{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel article - ActuG{% endblock %}

{% block body %}
    
    {% if app.user %}
    <h1 class="font-weight-normal text-center mb-4">Créer un nouvel article</h1>

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                {{ include('article/_form.html.twig', {'button_label': 'Créer'}) }}
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }} - ActuG{% endblock %}

{% block body %}
    <h1 class="font-weight-normal mb-4">{{ article.title }}</h1><br>

    <span><em>Publié le {{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</em> à <em>{{ article.createdAt|date('H:i')}}</em> par 
        <em>{{ article.userId.firstname }} {{ article.userId.lastname }}</em>
        {% if article.updatedAt %}
            (Modifié(e) le <em>{{ article.updatedAt ? article.updatedAt|date('Y-m-d') : '' }}</em> à <em>{{ article.updatedAt|date('H:i')}}</em>)
        {% endif %}
        </span><br><br>

    <img class='miniature' src="{{ asset('assets/images/articles/' ~ article.imageName) }}">

    <p>{{ article.content }}</p>

    <div class="mt-4">
        {% if app.user %}
            {% if article.userId.id == app.user.id %}
                <a href="{{ path('app_article_edit', {'id': article.id}) }}" class="btn btn-block btn-signup me-3"><i class="fa-solid fa-pen-to-square"></i></a>
            {% endif %}
        {% endif %}
        <a href="{{ path('app_article_index') }}" class="btn btn-outline btn-login">Retour à la liste</a>
    </div>
    <div class="mt-4">
        {% if app.user %}
            {% if is_granted('ROLE_ADMIN') or article.userId.id == app.user.id %}
                {{ include('article/_delete_form.html.twig') }}
            {% endif %}
        {% endif %}
    </div>
    <h2>Commentaires</h2>
    {% if app.user %}
        {{ include('comment/_form.html.twig', {'form': form, 'articleId': article.id}) }}
    {% endif %}
    {% for comment in comments %}
        <div class="comment-container">
            <p>"{{ comment.content }}"</p>
            <p>Commenté(e) par <em>{{ comment.userId.firstname }}</em>, le <em>{{ comment.createdAt|date('d/m/Y') }}</em> à <em>{{ comment.createdAt|date('H:i') }}</em>
            {% if comment.updatedAt %}
                (modifié(e) le <em>{{ comment.updatedAt|date('d/m/Y') }}</em> à <em>{{ comment.updatedAt|date('H:i')}}</em>)</p>
            {% endif %}
            {% if app.user %}
                {% if comment.userId.id == app.user.id %}
                    <a href="{{ path('app_comment_edit', {'id': comment.id, 'articleId': article.id}) }}" class="btn btn-block btn-signup me-3"><i class="fa-solid fa-pen-to-square"></i></a>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') or comment.userId.id == app.user.id %}
                    {{ include('comment/_delete_form.html.twig') }}
                {% endif %}
                {% if comment.reported %}
                    <p>Déjà signalé - en cours d'examen</p>
                {% else %}
                    <form action="{{ path('app_comment_report', {'id': comment.id}) }}" method="post">
                        <button type="submit" class="btn btn-outline btn-warning btn-login">Signaler</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
    {% endfor %}
    
{% endblock %}